#! /bin/sh
### BEGIN INIT INFO
# Provides:          linuxfr
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the linuxfr rails app
### END INIT INFO

set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=linuxfr

. /etc/default/$NAME

do_start() {
  # Work around "Launchy" failure when creating accounts.
  export BROWSER=w3m

  cd $RAILS_DIR && script/rails server -d -e $RAILS_ENV -P $PIDFILE
}

do_stop() {
  kill `cat $PIDFILE`
}

case "$1" in
  start)
    echo "Starting $NAME"
    do_start
    echo "."
    ;;

  stop)
    echo "Stopping $NAME"
    do_stop
    echo "."
    ;;

  force-reload|restart)
    echo "Restarting $NAME"
    do_stop
    sleep 10s
    do_start
    echo "."
    ;;

  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|force-reload|restart}"
    exit 1
esac

exit 0
